/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddingGameRouteImport } from './routes/adding-game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesMazeLevelRouteImport } from './routes/games/maze/$level'

const AddingGameRoute = AddingGameRouteImport.update({
  id: '/adding-game',
  path: '/adding-game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMazeLevelRoute = GamesMazeLevelRouteImport.update({
  id: '/games/maze/$level',
  path: '/games/maze/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adding-game': typeof AddingGameRoute
  '/games/maze/$level': typeof GamesMazeLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adding-game': typeof AddingGameRoute
  '/games/maze/$level': typeof GamesMazeLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adding-game': typeof AddingGameRoute
  '/games/maze/$level': typeof GamesMazeLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adding-game' | '/games/maze/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adding-game' | '/games/maze/$level'
  id: '__root__' | '/' | '/adding-game' | '/games/maze/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddingGameRoute: typeof AddingGameRoute
  GamesMazeLevelRoute: typeof GamesMazeLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/adding-game': {
      id: '/adding-game'
      path: '/adding-game'
      fullPath: '/adding-game'
      preLoaderRoute: typeof AddingGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/maze/$level': {
      id: '/games/maze/$level'
      path: '/games/maze/$level'
      fullPath: '/games/maze/$level'
      preLoaderRoute: typeof GamesMazeLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddingGameRoute: AddingGameRoute,
  GamesMazeLevelRoute: GamesMazeLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
