/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StageStageIdVariantRouteImport } from './routes/stage/$stageId.$variant'
import { Route as AnswerStageIdVariantRouteImport } from './routes/answer/$stageId.$variant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageStageIdVariantRoute = StageStageIdVariantRouteImport.update({
  id: '/stage/$stageId/$variant',
  path: '/stage/$stageId/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerStageIdVariantRoute = AnswerStageIdVariantRouteImport.update({
  id: '/answer/$stageId/$variant',
  path: '/answer/$stageId/$variant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer/$stageId/$variant': typeof AnswerStageIdVariantRoute
  '/stage/$stageId/$variant': typeof StageStageIdVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer/$stageId/$variant': typeof AnswerStageIdVariantRoute
  '/stage/$stageId/$variant': typeof StageStageIdVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer/$stageId/$variant': typeof AnswerStageIdVariantRoute
  '/stage/$stageId/$variant': typeof StageStageIdVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/answer/$stageId/$variant' | '/stage/$stageId/$variant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/answer/$stageId/$variant' | '/stage/$stageId/$variant'
  id:
    | '__root__'
    | '/'
    | '/answer/$stageId/$variant'
    | '/stage/$stageId/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerStageIdVariantRoute: typeof AnswerStageIdVariantRoute
  StageStageIdVariantRoute: typeof StageStageIdVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage/$stageId/$variant': {
      id: '/stage/$stageId/$variant'
      path: '/stage/$stageId/$variant'
      fullPath: '/stage/$stageId/$variant'
      preLoaderRoute: typeof StageStageIdVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/$stageId/$variant': {
      id: '/answer/$stageId/$variant'
      path: '/answer/$stageId/$variant'
      fullPath: '/answer/$stageId/$variant'
      preLoaderRoute: typeof AnswerStageIdVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerStageIdVariantRoute: AnswerStageIdVariantRoute,
  StageStageIdVariantRoute: StageStageIdVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
