import { defineConfig, devices } from "@playwright/test";

const isCI = !!process.env.CI;

// Generated apps use non-canonical ports so they can run their own Playwright
// suite alongside `apps/web` (6006 / 3000) without colliding on Storybook's
// dev server. Same defaults across every generated app — change here, not in
// the materialized config (which is gitignored and regenerated by /five-phase-pass).
const STORYBOOK_PORT = 6010;
const PREVIEW_PORT = 3010;

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: isCI,
  retries: isCI ? 2 : 0,
  ...(isCI ? { workers: 1 } : {}),
  reporter: [["list"], ["html", { open: "never" }]],

  use: {
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    testIdAttribute: "data-test",
    // Pillar — animations don't add flake. The useAnime hook short-circuits
    // when reducedMotion is "reduce". Set on contextOptions for cross-version
    // typing compatibility (Playwright 1.59).
    contextOptions: { reducedMotion: "reduce" },
  },

  projects: [
    {
      name: "storybook",
      testMatch: /.*\.story\.spec\.ts/,
      use: { ...devices["Desktop Chrome"], baseURL: `http://localhost:${STORYBOOK_PORT}` },
    },
    {
      name: "app",
      testMatch: /.*\.app\.spec\.ts/,
      use: { ...devices["Desktop Chrome"], baseURL: `http://localhost:${PREVIEW_PORT}` },
    },
    {
      name: "app-offline",
      testMatch: /.*\.offline\.spec\.ts/,
      use: { ...devices["Desktop Chrome"], baseURL: `http://localhost:${PREVIEW_PORT}` },
    },
  ],

  webServer: [
    {
      command: "bun run storybook",
      url: `http://localhost:${STORYBOOK_PORT}`,
      reuseExistingServer: !process.env.CI,
      // 3 min — covers Storybook's first-run Vite cold-prebundle after a dep change,
      // when parallel test workers can race the prebundler and hit ERR_CONNECTION_REFUSED.
      timeout: 180_000,
    },
    {
      command: "bun run preview",
      url: `http://localhost:${PREVIEW_PORT}`,
      reuseExistingServer: !process.env.CI,
      timeout: 120_000,
    },
  ],
});
